<?php

namespace Descolar\Adapters\Error\Handlers;

use Whoops\Handler\Handler;

class CustomHandler extends Handler
{

    private Handler $handler;

    public function __construct(Handler $handler)
    {
        $this->handler = $handler;
    }

    public function getHandler(): Handler
    {
        return $this->handler;
    }

    public function getException(): \Throwable
    {
        return $this->getInspector()->getException();
    }

    public function getInspector()
    {
        return parent::getInspector(); // TODO: Change the autogenerated stub
    }

    #[\Override] public function handle(): void
    {
        $exception = $this->getException();
        $httpCode = $this->getStatusCodeFromException($exception);

        $responseData = [
            'message' => $exception->getMessage(), // Vous pouvez personnaliser le contenu de la réponse selon vos besoins
            'error' => true
        ];

        $response = new Response(
            json_encode($responseData),
            $httpCode
        );

        $response->headers->set('Content-Type', 'application/json');

        $this->sendHttpCode($response);
    }
}